# users = {370795834:["p"]}
users = {}
books = {"Introduction to Algorithms": ["Introduction to Algorithms",
                                        ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                         "Clifford Stein"], "MIT Press", 2009,
                                        "Really good description"],
         "Introduction to Algorithms1": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms2": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms3": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms4": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms5": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms6": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms7": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms8": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms9": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],
         "Introduction to Algorithms0": ["Introduction to Algorithms",
                                         ["Thomas H. Cormen", "Charles E. Leiserson", "RonaldL. Rivest",
                                          "Clifford Stein"], "MIT Press", 2009,
                                         "Really good description"],

         }
